# Generated by Django 6.0.2 on 2026-02-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=15, unique=True)),
                ('_first_name', models.TextField(blank=True, default='')),
                ('_last_name', models.TextField(blank=True, default='')),
                ('_email', models.TextField(blank=True, default='')),
                ('_phone', models.TextField(blank=True, default='')),
                ('_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User (NFC)',
                'verbose_name_plural': 'Users (NFC)',
                'ordering': ['user_id'],
            },
        ),
    ]
