# Generated by Django 6.0.2 on 2026-02-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('date_of_birth', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=32)),
                ('blood_type', models.CharField(max_length=16)),
                ('nfc_id', models.CharField(db_index=True, max_length=15, unique=True)),
                ('status', models.CharField(max_length=32)),
                ('room', models.CharField(max_length=64)),
                ('admission_date', models.CharField(max_length=32)),
                ('allergies', models.JSONField(default=list)),
                ('primary_diagnosis', models.CharField(max_length=256)),
                ('insurance_provider', models.CharField(max_length=128)),
                ('insurance_id', models.CharField(max_length=128)),
                ('emergency_contact', models.JSONField(default=dict)),
                ('medications', models.JSONField(default=list)),
                ('vital_signs', models.JSONField(default=dict)),
                ('medical_history', models.JSONField(default=list)),
                ('notes', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
