# Generated by Django 6.0.2 on 2026-02-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfc_users', '0007_patientoutcomeevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientOutcomeEvent',
        ),
    ]
